version: "3"
services:
  server:
    image: server
    ports:
      - "8000:8000"
    networks:
      - my-net
  client:
    image: client
    ports:
      - "8090:8090"
    networks:
      - my-net
networks:
  my-net:
